export const RECOMMENDED_PRODUCTS = [
    {
        "video": "",
        "name": "Legendary Whitetails Journeyman Shirt Jacket, Flannel Lined Shacket for Men, Water-Resistant Coat Rugged Fall Clothing",
        "discount": 20,
        "numReviews": 571,
        "rating": 4.6,
        "isFeature": false,
        "brand": "Legendary",
        "price": 89.99,
        "description": "[Fit & Sizing]: For the signature Legendary Whitetails fit, see our size chart which accomodiates Standard and Big & Tall sizes; the Journeyman shirt jacket is designed for extra layering [Material & Durability]: Experience the Legendary Whitetails men's jacket quality with a blend of Cotton and Polyester; its rugged waxed cotton suede appearance, softer to the touch, promises durability and is weather-resistant[Warmth & Comfort]: Top quality flannel-lined for ultimate warmth, the Legendary Whitetails Journeyman is your shield against cold, transitional jacket for every season.",
        "category": "Men",
        "subcategory": "Jacket",
        "topDeal": true,
        "bestSeller": false,
        "countInStock": 17,
        "image": [
          "https://m.media-amazon.com/images/I/912xgelNpdL._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/81Aclfhd0SL._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/71QEpF7EGEL._AC_SX569_.jpg"
  
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0001",
      },
  
      {
        "video": "",
        "name": "Legendary Whitetails Men's Rugged Full Zip Dakota Jacket",
        "discount": 15,
        "numReviews": 320,
        "rating": 4.1,
        "isFeature": false,
        "brand": "Legendary",
        "price": 115.19,
        "description": "Cotton suede shell.Full front zipper, snap cuffs.Removable Hood. 5 Pockets: 2 Front, 1 Zippered Chest, 2 Inside.Signature Buck logo on hood",
        "category": "Men",
        "subcategory": "Jacket",
        "topDeal": true,
        "bestSeller": false,
        "countInStock": 9,
        "image": [
          "https://m.media-amazon.com/images/I/81RXgfs+IjL._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/81Qw2+j-msL._AC_SX425_.jpg",
          "https://m.media-amazon.com/images/I/815G1YfBKoL._AC_SX569_.jpg"
  
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0002",
      },
  
      {
        "video": "",
        "name": "Legendary Whitetails Men's Archer Flannel Thermal Lined Shirt Jacket, Quilted Insulated Plaid Work Outerwear Coat",
        "discount": 0,
        "numReviews": 221,
        "rating": 3.6,
        "isFeature": true,
        "brand": "Legendary",
        "price": 69.99,
        "description": "60% Cotton, 40% Polyester, Imported, [Fit & Quality]: True to size; for the signature Legendary Whitetails men's fit, refer to our size chart; this flannel shirt jacket is crafted with high-quality construction and detail, ensuring durability and a timeless look [Material & Warmth]: High quality construction and detail make this insulated flannel a standout Legendary shirt jac; coat features a 100% top quality cotton/poly blend thermal lining in the body, and smooth lined quilted sleeves; full poly-fill insulation and convenient side-seam pockets ensures you stay warm from cuff to cuff, making it a top choice among flannel shirt jackets for men [Color Fading]: Made of yarn-dyed 100% cotton plaid, this shirt jacket offers a crisper, sharper look; it's also a quick way to tell you're getting a high quality shirt; trust in our fade-resistant fabric to keep your men's flannel long sleeve shirt looking as vibrant as day one, wash after wash; the yarn-dyed plaid pattern showcases a high-quality design, setting you apart",
        "category": "Men",
        "subcategory": "Flannel",
        "topDeal": true,
        "bestSeller": false,
        "countInStock": 17,
        "image": [
          "https://m.media-amazon.com/images/I/81AGBVroP3L._AC_SX679_.jpg",
          "https://m.media-amazon.com/images/I/81jqHPnZ7ZL._AC_SX679_.jpg",
          "https://m.media-amazon.com/images/I/815u5RNqPQL._AC_SX679_.jpg"
  
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0003",
      },
  
      {
        "video": "",
        "name": "Legendary Whitetails Men's Maplewood Hooded Shirt Jacket",
        "discount": 25,
        "numReviews": 1220,
        "rating": 4.0,
        "isFeature": false,
        "brand": "Legendary",
        "price": 96.42,
        "description": "Quilted satin lined body and sleeves,130 gm of poly-fill insulation, Zippered entry placket and double lined fleece hood, Convenient side hand warming pockets, Legendary buttons and Signature Buck logo embroidery ",
        "category": "Men",
        "subcategory": "Jacket",
        "topDeal": true,
        "bestSeller": true,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/81JprHUYo6L._AC_SY550_.jpg",
          "https://m.media-amazon.com/images/I/81JtZD62pdL._AC_SY550_.jpg",
          "https://m.media-amazon.com/images/I/716jU-YNbfL._AC_SX569_.jpg"
  
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0004",
      },
      {
        "video": "",
        "name": "Legendary Whitetails Men's Tough as Buck Outdoorsman Wool Coat, Winter Outerwear Jacket, Insulated Work Clothing",
        "discount": 0,
        "numReviews": 105,
        "rating": 3.8,
        "isFeature": false,
        "brand": "Legendary",
        "price": 99.99,
        "description": "[Fit & Legendary Whitetails Quality]: True to size; for the signature Legendary Whitetails men's Regular fit, refer to our size chart; this wool coat, a standout among men's wool coats, promises durability, warmth, and a timeless look[Material & Sustainability]: Crafted with recycled wool, this men's coat is very warm; the blend of acrylic, polyester, nylon, and viscose ensures durability, making it a top choice for those searching for warm men's wool coats and jackets[Comfort & Warmth]: Warm Sherpa fleece is popular for a reason; soft to the touch and great at trapping body heat, it ensures core warmth while kicking your comfort level up a notch; the quilted",
        "category": "Men",
        "subcategory": "Jacket",
        "topDeal": false,
        "bestSeller": false,
        "countInStock": 20,
        "image": [
          "https://m.media-amazon.com/images/I/917ZdNtUv+L._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/91185RUtaLL._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/916tY+nzSZL._AC_SX569_.jpg"
  
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0005",
      },
      {
        "video": "",
        "name": "Legendary Whitetails Men's Stockyards Bozeman Canvas Western Coat",
        "discount": 0,
        "numReviews": 2055,
        "rating": 4.3,
        "isFeature": true,
        "brand": "Legendary",
        "price": 119.99,
        "description": "Durable water-repellent finish. Removable 3-panel hood. Diamond stitch quilted flannel lining. Adjustable cuffs and polyester lined sleeves.Bottom band snap closure",
        "category": "Men",
        "subcategory": "Jacket",
        "topDeal": false,
        "bestSeller": true,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/81mPxzB1xVL._AC_SX679_.jpg",
          "https://m.media-amazon.com/images/I/81Nx-3Ci-lL._AC_SX679_.jpg",
          "https://m.media-amazon.com/images/I/91cgHlZJLEL._AC_SX522_.jpg"
  
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0006",
      },
      {
        "video": "",
        "name": "Legendary Whitetails Men's Glacier Ridge Pro Series Winter Coat",
        "discount": 0,
        "numReviews": 1120,
        "rating": 4.8,
        "isFeature": true,
        "brand": "Legendary",
        "price": 149.99,
        "description": "Provides exceptional warmth without the bulk.Perfect for any extreme cold weather activities. Water resistant, features a built in membrane to ensure you keep the water out.Zippered under arm vents and removable hood allow you to change your garment as the weather changes.Complete with reflective piping, adjustable cuffs, and 6 pockets",
        "category": "Men",
        "subcategory": "Jacket",
        "topDeal": false,
        "bestSeller": true,
        "countInStock": 15,
        "image": [
          "https://m.media-amazon.com/images/I/81vsGouHylL._AC_SX569_.jpg",
          "https://m.media-amazon.com/images/I/810H+yS8kyL._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/919VKPi6SKL._AC_SX522_.jpg"
  
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0007",
      },
      {
        "video": "",
        "name": "Legendary Whitetails Men's Big Game Camo Snow Outfitter Hoodie",
        "discount": 10,
        "numReviews": 20,
        "rating": 3,
        "isFeature": true,
        "brand": "Legendary",
        "price": 39.21,
        "description": "Authentic cut-through Signature Buck applique. Cotton/spandex blend cuffs. Hand warmer style front pocket.  Matching braided cotton drawstring. Legendary embroidered on the edge of the hood",
        "category": "Men",
        "subcategory": "hoodies",
        "topDeal": true,
        "bestSeller": false,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/81CLl+ljl+L._AC_SX569_.jpg",
          "https://m.media-amazon.com/images/I/71otKt2gwWL._AC_SX569_.jpg",
          
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0008",
      },
      {
        "video": "",
        "name": "Legendary Whitetails Men's Maverick Slub Henley Short Sleeve Shirt",
        "discount": 10,
        "numReviews": 20,
        "rating": 4,
        "isFeature": true,
        "brand": "Legendary",
        "price": 31.99,
        "description": "Henley neckline with 4 button placket pull on closure. Contrast stitching along the sleeves and hemline. Tagless neck label for comfort.Legendary embroidered on back yoke. Legendary Signature Buck logo patch on hemline",
        "category": "Men",
        "subcategory": "Shirt",
        "topDeal": false,
        "bestSeller": false,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/71W+TZX4Q9L._AC_SX569_.jpg",
          "https://m.media-amazon.com/images/I/71Mi1GLZ3FL._AC_SX569_.jpg",
          "https://m.media-amazon.com/images/I/61QwELB8CoL._AC_SX569_.jpg"
          
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0009",
      },
      {
        "video": "",
        "name": "Legendary Whitetails Men's Maverick Slub Henley Shirt",
        "discount": 0,
        "numReviews": 350,
        "rating": 4.7,
        "isFeature": true,
        "brand": "Legendary",
        "price": 39.99,
        "description": "Extremely soft comfortable fabric. Four button placket pullover shirt. Contrast stitching.Legendary branded back yoke.Legendary Signature Buck tag on hem",
        "category": "Men",
        "subcategory": "Shirt",
        "topDeal": false,
        "bestSeller": false,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/71y0lAA36-L._AC_SX569_.jpg",
          "https://m.media-amazon.com/images/I/71hsjtM5HKL._AC_SX425_.jpg",
          "https://m.media-amazon.com/images/I/91Glb4LW66L._AC_SX466_.jpg"
          
        ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0010",
      },
      {
        "video": "",
        "name": "Legendary Whitetails Men's Recluse Henley",
        "discount": 15,
        "numReviews": 350,
        "rating": 4.8,
        "isFeature": true,
        "brand": "Legendary",
        "price": 39.99,
        "description": "Distressed seams for a rugged look.  Easy-moving raglan long sleeves. Soft, sueded finish. 4-button placket for easy on/off. Legendary label at hem",
        "category": "Men",
        "subcategory": "Shirt",
        "topDeal": false,
        "bestSeller": true,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/91VCk+J8s8L._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/91b68QiQUCL._AC_SX522_.jpg",
                ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0011",
      },
      {
        "video": "",
        "name": "Nautica Men's Classic Fit Interlock Polo",
        "discount": 0,
        "numReviews": 250,
        "rating": 3.0,
        "isFeature": false,
        "brand": "Nautica",
        "price": 28.57,
        "description": "Ribbed spread collar; partial button closures at front.Short sleeves; ribbed at cuffs. Classic-fit. Side vents; J-class logo at chest. Classic-fit interlocked polo",
        "category": "Men",
        "subcategory": "Shirt",
        "topDeal": false,
        "bestSeller": true,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/71S1DnUjdoL._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/81DadHEoBbL._AC_SX522_.jpg",
                ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0012"
      },
      {
        "video": "",
        "name": "Nautica Men's Navtech Colorblock Tee",
        "discount": 20,
        "numReviews": 250,
        "rating": 3.0,
        "isFeature": false,
        "brand": "Nautica",
        "price": 24.99,
        "description": "Crew neck; ribbed collar; slip-on style.  Short sleeves. One-fit. J-class logo at hem; Nautica logo at chest. Colorblock Navtech t-shirt",
        "category": "Men",
        "subcategory": "Shirt",
        "topDeal": false,
        "bestSeller": true,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/71e0w6RNEjL._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/71cdvQYCxhL._AC_SX466_.jpg",
                ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0013"
      },
      {
        "video": "",
        "name": "Nautica Men's Short Sleeve Color Block Performance Pique Polo Shirt",
        "discount": 30,
        "numReviews": 1250,
        "rating": 4.5,
        "isFeature": false,
        "brand": "Nautica",
        "price": 34.99,
        "description": "Vented hem for a little extra mobility; moisture-wicking fabric keeps you dry and comfortable. Performance polo with classic fit and moisture-wicking fabrication",
        "category": "Men",
        "subcategory": "Shirt",
        "topDeal": true,
        "bestSeller": false,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/81z6nBT9X2L._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/71DnhkEQZlL._AC_SY550_.jpg",
                ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0014"
      },
      {
        "video": "",
        "name": "Nautica Men's Classic Fit 100% Cotton Soft Short Sleeve Stripe Polo Shirt",
        "discount": 0,
        "numReviews": 150,
        "rating": 3.8,
        "isFeature": false,
        "brand": "Nautica",
        "price": 36.59,
        "description": "A vented hem gives you a little extra room to move.Classic fit polo shirt with a striped design and sporty styling",
        "category": "Men",
        "subcategory": "Shirt",
        "topDeal": false,
        "bestSeller": false,
        "countInStock": 11,
        "image": [
          "https://m.media-amazon.com/images/I/91FiVDNJvmL._AC_SX569_.jpg",
          "https://m.media-amazon.com/images/I/91jpuhEPjQL._AC_SY550_.jpg",
                ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0015"
      },
      {
        "video": "",
        "name": "Nautica Men's Classic Fit Short Sleeve Dual Tipped Collar Polo Shirt",
        "discount": 0,
        "numReviews": 33,
        "rating": 3.8,
        "isFeature": false,
        "brand": "Nautica",
        "price": 26.50,
        "description": "Solid stand collar polo with ribbing and classic fit.Stand collar, 3-button placket closure",
        "category": "Men",
        "subcategory": "Shirt",
        "topDeal": false,
        "bestSeller": false,
        "countInStock": 17,
        "image": [
          "https://m.media-amazon.com/images/I/81NoIwsvrAL._AC_SX522_.jpg",
          "https://m.media-amazon.com/images/I/81ZphX+AtAL._AC_SY550_.jpg",
               ],
        "sizes": ["S", "M", "L", "XL"],
        "id": "0016"
      }
]

export const QUICK_OFFERS = [
    {
        id: "5526",
        name: "Flannel",
        discount: "-25%",
        image: "https://m.media-amazon.com/images/I/81AGBVroP3L._AC_SX679_.jpg",
    },
    {
        id: "534526", 
        name: "Hoodies",
        discount: "-15%",
        image: "https://m.media-amazon.com/images/I/81CLl+ljl+L._AC_SX569_.jpg",
    },
    {
        id: "532456",
        name: "Jacket",
        discount: "-20%",
        image: "https://m.media-amazon.com/images/I/81JprHUYo6L._AC_SY550_.jpg",
    },
    {
        id: "24526",
        name: "Shirt",
        discount: "-35%",
        image: "https://m.media-amazon.com/images/I/71W+TZX4Q9L._AC_SX569_.jpg",
    },
    {
        id: "4526",
        name: "Pullover",
        image: "https://m.media-amazon.com/images/I/81uh8z1IRwL._AC_SX522_.jpg",
    },
    {
      id: "24554",
      name: "Shirt",
      discount: "-35%",
      image: "https://m.media-amazon.com/images/I/71W+TZX4Q9L._AC_SX569_.jpg",
  },
  {
    id: "24555",
    name: "Shirt",
    discount: "-35%",
    image: "https://m.media-amazon.com/images/I/71W+TZX4Q9L._AC_SX569_.jpg",
},
]

export const TRENDING_CATEGORIES = [
    {
        id: 1,
        name: "Fannels",
        image: "/lenador.jpg",
        link:"/search?category=Flannel"
    },
    {
        id: 2,
        name: "Shirts",
        image: "/cow6.jpg",
        link:"/search?category=Shirt"
    },
    {
        id: 3,
        name: "Accesories",
        image: "/accesories.jpg",
        link:"/search?category=Accesories"
    },
    {
      id: 4,
      name: "Jackets",
      image: "/advertise.jpg",
      link:"/search?category=Jacket"
  },
]
